AMSBIOintranet/AMSBIOintranet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('homepage.urls')),
    path('myDatabase/',include('myDatabase.urls')),
    path('Courier/',include('Courier.urls')),
    path('admin/', admin.site.urls),
]

AMSBIOintranet/Courier/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index',views.index, name = 'index'),
    path('FedexUK',views.fedex, name='fedex' ),
    path('FedexUSA',views.fedex, name='fedex' ),
    path('DHL',views.dhl, name='dhl' ),
    path('loadtable_UK',views.loadCSVtoHTML, name='loadtable_UK'),
    path('loadtable_USA',views.loadCSVtoHTML, name='loadtable_USA'),
]

AMSBIOintranet/myDatabase/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
import regex as re
from math import ceil

from homepage.models import liveCurrencyRate


class Currencies(models.Model):
    # Field name made lowercase.
    currencyid = models.AutoField(db_column='CurrencyID', primary_key=True)
    # Field name made lowercase.
    descriptive = models.CharField(db_column='Descriptive', max_length=16)
    # Field name made lowercase.
    comments = models.CharField(db_column='Comments', max_length=45)
    dimmensions_currency_symbol = models.CharField(max_length=4)

    def __str__(self):
        return self.descriptive
        

    class Meta:
        db_table = 'currencies'
        app_label = 'myDatabase'
        verbose_name_plural = "Currencies"
    

class DataOwners(models.Model):
    dat_id = models.AutoField(primary_key=True)
    # Field name made lowercase.
    owner = models.CharField(db_column='Owner', max_length=64)
    # Field name made lowercase.
    supplierpurchasecurrency = models.CharField(
        db_column='SupplierPurchaseCurrency', max_length=4, blank=True, null=True)
    productpurchasebrand = models.PositiveIntegerField(
        db_column='ProductPurchaseBrand', blank=True, null=True, default=1)  # Field name made lowercase.
    productsellingbrand = models.PositiveIntegerField(
        db_column='ProductSellingBrand', blank=True, null=True, default=1)  # Field name made lowercase.
    # Field name made lowercase.
    dimmensionssuppliercode = models.CharField(
        db_column='DimmensionsSupplierCode', max_length=10, blank=True, null=True)
    dimmensionsproductgroup = models.PositiveIntegerField(
        db_column='DimmensionsProductGroup', blank=True, null=True, default=1)  # Field name made lowercase.
    # Field name made lowercase.
    msaccessdatid = models.PositiveIntegerField(
        db_column='MsAccessDatId', blank=True, null=True, default=1)
    # Field name made lowercase.
    datasheetsuffix = models.CharField(
        db_column='DatasheetSuffix', max_length=4, blank=True, null=True, default=1)
    logo_url = models.CharField(max_length=128, blank=True, null=True, default=1)
    web_site_sql_id = models.PositiveIntegerField(blank=True, null=True, default=1)
    precedence_listing = models.PositiveIntegerField(blank=True, null=True, default=1)
    web_site_url = models.CharField(max_length=45, blank=True, null=True, default=1)
    ik_flag_id = models.PositiveIntegerField(blank=True, null=True, default=1)
    currencyid = models.PositiveIntegerField(blank=True, null=True)
    usa_market_flag_id = models.PositiveIntegerField(blank=True, null=True, default=1)

    def __str__(self):
        return self.owner

    class Meta:
        db_table = 'data_owners'
        app_label = 'myDatabase'
        verbose_name_plural = "Data Owners"
  

class MasterCurrencies(models.Model):
    mstr_cur_id = models.AutoField(primary_key=True)
    from_currency_id = models.PositiveIntegerField()
    to_currency_id = models.PositiveIntegerField()
    exchange_rate = models.FloatField()

    def symbolfrom(self):
        symbol = [1,2,3,4,6,7]
        if self.from_currency_id in symbol:
                return Currencies.objects.get(pk=self.from_currency_id).descriptive

    def symbolto(self):
        symbol = [1,2,3,4,6,7]
        if self.to_currency_id in symbol:
                return Currencies.objects.get(pk=self.to_currency_id).descriptive

    def liverate(self):
        return liveCurrencyRate.objects.get(base_currency=self.symbolfrom(),to_currency=self.symbolto()).live_rate
    
    def diff(self):
        return round(self.liverate() - self.exchange_rate, 3)
           
    class Meta:
        db_table = 'master_currencies'
        app_label = 'myDatabase'
        verbose_name_plural = "Master Currencies"


class ProductRecords(models.Model):
    product_code = models.CharField(primary_key=True, max_length=64)
    supplier_product_code = models.CharField(
        max_length=64, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    long_description = models.TextField(blank=True, null=True)
    packsize = models.CharField(max_length=256, blank=True, null=True)
    purchase_nett_price = models.FloatField(blank=True, null=True)
    supplier_list_price = models.FloatField(blank=True, null=True)
    sell_price_gbp = models.FloatField(blank=True, null=True)
    sell_price_eur = models.FloatField(blank=True, null=True)
    sell_price_chf = models.FloatField(blank=True, null=True)
    sell_price_usd = models.FloatField(blank=True, null=True)
    storage_conditions = models.TextField(blank=True, null=True)
    shipping_temperature = models.TextField(blank=True, null=True)
    commodity_code = models.TextField(blank=True, null=True)
    category_1 = models.IntegerField(blank=True, null=True)
    category_2 = models.IntegerField(blank=True, null=True)
    research_area_1 = models.IntegerField(blank=True, null=True)
    research_area_2 = models.IntegerField(blank=True, null=True)
    research_area_3 = models.IntegerField(blank=True, null=True)
    research_area_4 = models.IntegerField(blank=True, null=True)
    supplier_category_1 = models.TextField(blank=True, null=True)
    supplier_category_2 = models.TextField(blank=True, null=True)
    supplier_category_3 = models.TextField(blank=True, null=True)
    supplier_lead_time = models.TextField(blank=True, null=True)
    ct_supplier_id = models.IntegerField(blank=True, null=True)
    delete_flag = models.IntegerField(blank=True, null=True)
    listing_precedence = models.IntegerField(blank=True, null=True)
    last_updated_user = models.CharField(max_length=64, blank=True, null=True)
    last_change_date = models.DateTimeField(blank=True, null=True)
    price_calculation_type = models.PositiveIntegerField(blank=True, null=True)
    website_flag = models.IntegerField(blank=True, null=True)
    new_product_flag = models.IntegerField(blank=True, null=True)
    previous_purchase_price = models.FloatField(blank=True, null=True)
    price_change_flag = models.IntegerField(blank=True, null=True)
    price_change_percent = models.FloatField(blank=True, null=True)
    is_in_website = models.IntegerField(blank=True, null=True)
    is_in_odoo = models.IntegerField(blank=True, null=True)
    special_shipping = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'product_records'
        app_label = 'myDatabase'

    def suppliername(self):
        return DataOwners.objects.get(pk=self.ct_supplier_id).owner

    def supplierCurrency(self):
        return DataOwners.objects.get(pk=self.ct_supplier_id).supplierpurchasecurrency
    
    def cat1(self):
        lev1 = NwCategoryLowestNodes.objects.get(pk=self.category_1).level1
        lev2 = NwCategoryLowestNodes.objects.get(pk=self.category_1).level2
        lev3 = NwCategoryLowestNodes.objects.get(pk=self.category_1).level3
        if lev2 == 0:
            return NwCategoryIds.objects.get(pk=lev1).category_name
        elif lev3 == 0 and lev2 != 0:
            return str(NwCategoryIds.objects.get(pk=lev1).category_name) + " >> " + str(NwCategoryIds.objects.get(pk=lev2).category_name)  
        else:
            return str(NwCategoryIds.objects.get(pk=lev1).category_name) + " >> " + str(NwCategoryIds.objects.get(pk=lev2).category_name) + " >> " + str(NwCategoryIds.objects.get(pk=lev3).category_name)
    
    def cat2(self):
        lev1 = NwCategoryLowestNodes.objects.get(pk=self.category_2).level1
        lev2 = NwCategoryLowestNodes.objects.get(pk=self.category_2).level2
        lev3 = NwCategoryLowestNodes.objects.get(pk=self.category_2).level3
        if lev2 == 0:
            return NwCategoryIds.objects.get(pk=lev1).category_name
        elif lev3 == 0 and lev2 != 0:
            return str(NwCategoryIds.objects.get(pk=lev1).category_name) + " >> " + str(NwCategoryIds.objects.get(pk=lev2).category_name)  
        else:
            return str(NwCategoryIds.objects.get(pk=lev1).category_name) + " >> " + str(NwCategoryIds.objects.get(pk=lev2).category_name) + " >> " + str(NwCategoryIds.objects.get(pk=lev3).category_name)        
    
    def research1(self):
        return NwResearchAreaIds.objects.get(pk=self.research_area_1).research_area

    def research2(self):
        return NwResearchAreaIds.objects.get(pk=self.research_area_2).research_area

    def research3(self):
        return NwResearchAreaIds.objects.get(pk=self.research_area_3).research_area

    def research4(self):
        return NwResearchAreaIds.objects.get(pk=self.research_area_4).research_area

    def purchasePriceGbp(self):
        currency = DataOwners.objects.get(pk=self.ct_supplier_id).supplierpurchasecurrency
        return round(self.purchase_nett_price*liveCurrencyRate.objects.get(base_currency=currency,to_currency="GBP").live_rate,3)

    def ug_ps(self):
        mlr = 1
        ps = self.packsize.replace('µ','u')
        outp = 0
        if 'x' in ps.lower():
            if '/ml' in ps.lower():
                ps = re.sub(r'([0-9\.]+) ?([mu]?g) ?/ ?ml ?x ?([0-9\.]+) ?ml',r'\1 x \3 \2',ps,re.IGNORECASE)
            mlr = float(re.findall('([0-9\.]{1,2}) ?x ?',ps,re.IGNORECASE)[0])
            ps = re.sub('[0-9]{1,2} ?x ?','',ps,re.IGNORECASE)

        if 'mg' in ps.lower():
            outp = mlr * float(re.findall('([0-9\.]{1,4}) ?mg',ps,re.IGNORECASE)[0]) * 1000
        elif re.match('^[0-9] ?g$',ps,re.IGNORECASE):
            outp = mlr * float(re.findall('([0-9\.]{1,4}) ?g',ps,re.IGNORECASE)[0]) * 1000000

AMSBIOintranet/myDatabase/forms.py
from .models import ProductRecords, ProductRecordsTech
from django import forms


# Django class for generating model form for 'ProductRecords' table
class EditProductForm(forms.ModelForm):
    sell_price_rest_of_world_usd = forms.CharField(max_length=64, disabled=True, required=False)

    def __init__(self, *args, **kwargs):
        super(EditProductForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs.update(
                {'class': 'form-control', 'rows': '0', 'cols': '10'})

    class Meta:
        model = ProductRecords
        fields = ["product_code",
                  "supplier_product_code",
                  "description",
                  "long_description",
                  "packsize",
                  "purchase_nett_price",
                  "supplier_list_price",
                  "sell_price_gbp",
                  "sell_price_eur",
                  "sell_price_chf",
                  "sell_price_usd",
                  "sell_price_rest_of_world_usd",
                  "storage_conditions",
                  "shipping_temperature",
                  "commodity_code",
                  "category_1",
                  "category_2",
                  "research_area_1",
                  "research_area_2",
                  "research_area_3",
                  "research_area_4",
                  "supplier_category_1",
                  "supplier_category_2",
                  "supplier_category_3",
                  "supplier_lead_time",
                  "ct_supplier_id",
                  "delete_flag",
                  "listing_precedence",
                  "last_updated_user",
                  "last_change_date",
                  "price_calculation_type",
                  "website_flag",
                  "new_product_flag",
                  "previous_purchase_price",
                  "price_change_flag",
                  "price_change_percent",
                  "is_in_website",
                  "is_in_odoo",
                  "special_shipping"]


# Django class for generating model form for 'ProductRecordsTech' table
class EditTechDetailsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditTechDetailsForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs.update(
                {'class': 'form-control', 'rows': '0', 'cols': '5'})

    class Meta:
        model = ProductRecordsTech
        fields = '__all__'

AMSBIOintranet/templates/button.html
<!-- template for rendering the attribute button on search.html page -->
<button id="getrecord{{record.pk}}" type="button" class="btn icofont-plus-circle"></button>
<!-- <button id="getrecord{{record.pk}}" type="button" class="btn icofont-plus-circle" data-toggle="collapse"
  data-target="#collapse{{record.pk}}" aria-expanded="false" aria-controls="collapse{{record.pk}}"
  value="{{record.pk}}"></button>
<div class="collapse" id="collapse{{record.pk}}" style="margin-top: 10px;">
  <div class="table-responsive" style="overflow-x: hidden;">
    Generates the respective Technical attribute table for every product
    <table id="techRecord{{record.pk}}" style="text-align: left; width: 100%;">
      <thead></thead>
      <tbody id="techRecordBody{{record.pk}}" style="height: 400px; display:block;">
        data comes from Ajax present at main.js
      </tbody>
    </table>
  </div>
</div> -->

AMSBIOintranet/templates/currencyval.html
{% load static %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Currency Values</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="{% static 'assets/img/favicon.JPG' %}" rel="icon">

  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">

  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center">

      <a href="index"><img class="header_img" src="{% static 'assets/img/amsbio_logo.png' %}" alt="amsbio_logo"></a>


      <nav class="nav-menu d-none d-lg-block">

        <ul>
          <li><a href="index">Home</a></li>

          <li class="drop-down"><a href=" ">Database</a>
            <ul>
              <li><a href="AddNewSupplier">Add New Supplier</a></li>
              <li><a href="Search">Search Products</a></li>
              <li><a href="EditSingleProduct/LoadDefaultView">Edit Single Product</a></li>
              <li><a href="similarProducts/3011-100">Similar Products</a></li>
              <li><a href="CurrencyValues">Currency Values</a></li>
            </ul>
          </li>
          <li class="drop-down"><a href="#">Courier</a>
            <ul>
              <li class="drop-down"><a href="#">FedEx</a>
                <ul>
                  <li><a href="../Courier/FedexUK">FedEx UK</a></li>
                  <li><a href="../Courier/FedexUSA">FedEx USA</a></li>
                </ul>
              </li>
              <li><a href="../Courier/DHL">DHL</a></li>
            </ul>
          </li>
        </ul>

      </nav>

    </div>
  </header>

  <main id="main">

    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Currency Values</h2>
          <ol>
            <li><a href="index">Home</a></li>
            <li>Currency Values</li>
          </ol>
        </div>

      </div>
    </section>

    <section id="testimonials" class="testimonials">
      <div class="container">
        <div style="text-align:right; margin-top: 5px;">
          <a href="{% querystring '_export'='csv' %}">Download CSV</a>
        </div>
        <div class="row" style="box-shadow: 0 8px 20px rgba(0,0,0,0.15);">
          <div class="col-md-12 border border-secondary rounded">
            <!-- renders the currency table as received from myDatabase/tables.py  -->
            {% render_table obj %}
          </div>
        </div>
      </div>
    </section>

  </main>

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>

  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

AMSBIOintranet/templates/editsingleprod.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Edit Single Product</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <link href="{% static 'assets/img/favicon.JPG' %}" rel="icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">

  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center">

      <a href="../../index"><img class="header_img" src="{% static 'assets/img/amsbio_logo.png' %}" alt="amsbio_logo"></a>


      <nav class="nav-menu d-none d-lg-block">

        <ul>
          <li><a href="../../index">Home</a></li>

          <li class="drop-down"><a href=" ">Database</a>
            <ul>
              <li><a href="../../AddNewSupplier">Add New Supplier</a></li>
              <li><a href="../../Search">Search Products</a></li>
              <li><a href="../../EditSingleProduct/LoadDefaultView">Edit Single Product</a></li>
              <li><a href="../../similarProducts/3011-100">Similar Products</a></li>
              <li><a href="../../CurrencyValues">Currency Values</a></li>
            </ul>
          </li>
          <li class="drop-down"><a href="#">Courier</a>
            <ul>
              <li class="drop-down"><a href="#">FedEx</a>
                <ul>
                  <li><a href="../../../Courier/FedexUK">FedEx UK</a></li>
                  <li><a href="../../../Courier/FedexUSA">FedEx USA</a></li>
                </ul>
              </li>
              <li><a href="../Courier/DHL">DHL</a></li>
            </ul>
          </li>
        </ul>

      </nav>

    </div>
  </header>

  <main id="main">

    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Edit Single Product</h2>
          <ol>
            <li><a href="../../index">Home</a></li>
            <li>Edit Single Product</li>
          </ol>
        </div>

      </div>
    </section>

    <section id="testimonials" class="testimonials">
      <div class="container text-center" style="margin-bottom: 20px;">
        <div class="row">
          <div class="col-md-12">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group row" style="padding-left: 25%; padding-right: 25%;">
                <div class="input-group col-sm-12">
                  <div class="input-group-prepend">
                    <div class="input-group-text">Product Code</div>
                  </div>
                  <input type="text" name="ProdCode" id="ProdCode" placeholder="Search" class="form-control">
                  <div class="input-group-append">
                    <button class="btn btn-danger" name="btnSubmitCode">Submit</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div >
      {% if flag %} <!--Output if proper product code is not entered-->
        <div class="container" style="text-align: center;">
            <i>{{msg}}</i>
        </div>
      {% else %}
        {% if nocategory %} <!--Output if no categories are defined-->
          <div class="row" style="padding-top: 10px; border-radius: 5px; background-color: #fafafa; width:85%; margin:auto;">
            <div id="prodform_container" class="col-md-6"> <!--Output only the Edit Product form-->
              <form id='ProdForm' method="POST">
                {% csrf_token %}
                <div class="form-group row" style="text-align: center; margin-bottom: 20px;">
                  <div class="col-sm-12">
                    <button class="btn btn-primary" disabled>Product Details</button>
                  </div>
                </div>
                {% for field in ProdForm %}
                  <div class="form-group{% if field.errors %} invalid{% endif %} row">
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label }}:</label>
                    <div class="col-sm-8">
                      {{ field }}
                    </div>
                    {% for error in field.errors %}
                      <p class="help-block">{{ error }}</p>
                    {% endfor %}
                  </div>
                {% endfor %}
                <button type="submit" class="btn btn-danger" id="btnProdForm" style="margin:auto; display:block; padding-top: 10px; margin-bottom: 10px;">Submit</button>
              </form>
            </div>
            <div class="col-md-6" style="padding: 2%; padding-left: 20%;"> <!--Display message for no categories-->
              <button class="btn btn-danger">{{NoTechCategory}}</button> 
            </div>
          </div>
          {% else %} <!--Output if categories are defined-->
          <div class="row" style="padding-top: 10px; border-radius: 5px; background-color: #fafafa; width:88%; margin:auto;">
            <div id="prodform_container" class="col-md-6" style="padding-right: 5%;"> <!--Output the Edit Product form-->
              <form id='ProdForm' method="POST">
                {% csrf_token %}
                <div class="form-group row" style="text-align: center; margin-bottom: 20px;">
                  <div class="col-sm-12">
                    <button class="btn btn-primary" disabled>Product Details</button>
                  </div>
                </div>
                {% for field in ProdForm %}
                <div class="form-group{% if field.errors %} invalid{% endif %} row">
                  <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label }}:</label>
                  <div class="col-sm-8">
                    {{ field }}
                  </div>
                  {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                  {% endfor %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-danger" style="margin:auto; display:block; padding-top: 10px; margin-bottom: 10px;">Submit</button>
              </form>
            </div>
            <div id="techform_container" class="col-md-6" style="padding-left: 5%;"> <!--Output the Edit Tech form-->
              <form id='TechForm' method="POST">
                {% csrf_token %}
                <div class="form-group row" style="text-align: center; margin-bottom: 20px;">
                  <div class="col-sm-12">
                    {% if catflag %}
                      <button class="btn btn-primary" disabled>{{cat1}}, {{cat2}}</button>
                    {% else %}
                      <button class="btn btn-primary" disabled>{{cat1}}</button>
                    {% endif %}
                  </div>
                </div>
                {% for field in TechForm %}
                  {% if field.id_for_label in attrs %}
                  <div class="form-group{% if field.errors %} invalid{% endif %} row">
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label }}:</label>
                    <div class="col-sm-8">
                      {{ field }}
                    </div>
                    {% for error in field.errors %}
                      <p class="help-block">{{ error }}</p>
                    {% endfor %}
                  </div>
                  {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-danger" style="margin:auto; display:block; padding-top: 10px; margin-bottom: 10px;">Submit</button>
              </form>
            </div>
          </div>
          {% endif %}
        </div>  
      {% endif %}
    </section>


  </main>


  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>

  <script src="{% static 'assets/js/main.js' %}"></script>

  <script type="text/javascript">
    var usd_sell_price = document.querySelector("#id_sell_price_usd").value;
    var rest_of_world_price = document.querySelector("#id_sell_price_rest_of_world_usd");
    var usd_price_float = parseFloat(usd_sell_price);
    rest_of_world_price.value = 5 * Math.ceil((usd_price_float * 1.2)/5);
  </script>
  
</body>

</html>